import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, addDoc, collection, query, where, onSnapshot, serverTimestamp, updateDoc, deleteDoc, orderBy } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyABpnRRv30zYTN0J_IReUgZPY88FSm9Omw',authDomain:'kurirtabin.firebaseapp.com',projectId:'kurirtabin',storageBucket:'kurirtabin.firebasestorage.app',messagingSenderId:'55763945350',appId:'1:55763945350:web:a06e1e51fea385aa494e07'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let user=null,profile=null,view='home',orders=[],products=[],customers=[],unsubscribeOrders=null,unsubscribeProducts=null,unsubscribeUsers=null,selectedOrder=null;
const demoProducts=[
  {id:'demo-bakso',name:'Bakso Sony',category:'Food',price:25000,icon:'🍜',active:true},
  {id:'demo-sembako',name:'Paket Sembako',category:'Belanja',price:50000,icon:'🛍️',active:true},
  {id:'demo-jastip',name:'Titip Belanja Bebas',category:'Jastip',price:10000,icon:'🛒',active:true}
];
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dt=v=>{try{if(!v)return '-';if(v.toDate)return v.toDate().toLocaleString('id-ID');return new Date(v).toLocaleString('id-ID')}catch{return '-'}};
function toast(m){const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function statusBadge(s){const c=s==='Selesai'?'green':s==='Dibatalkan'?'red':s==='Menunggu'?'orange':s==='Dikirim'||s==='Dijemput'?'green':'blue';return `<span class="badge ${c}">${esc(s||'Menunggu')}</span>`}
function logo(){return `<img src="assets/logo.png" alt="TB Express">`}
function topbar(admin=false){return `<header class="${admin?'admin-top':'topbar'}"><div class="${admin?'admin-top-inner':'topbar-inner'}"><div class="brand">${logo()}<div><div class="brand-title">TB Express</div><div class="brand-sub">Jastip & Kurir Tanjung Bintang</div></div></div>${admin?`<button class="btn btn-orange" id="logout">Keluar</button>`:`<div class="location"><span class="material-symbols-outlined">location_on</span>Tanjung Bintang</div>`}</div></header>`}
function bottom(){return `<nav class="bottom"><div class="bottom-inner">${[['home','Beranda','home'],['send','Kirim','local_shipping'],['orders','Pesanan','receipt_long'],['profile','Profil','person']].map(x=>`<button class="navbtn ${view===x[0]?'active':''}" data-nav="${x[0]}"><span class="material-symbols-outlined">${x[2]}</span>${x[1]}</button>`).join('')}</div></nav>`}
function customerLayout(content){$('#app').innerHTML=`<div class="shell">${topbar()}<main class="container mobile-container">${content}</main>${bottom()}</div>`;bindCommon()}
function home(){return `<section class="hero"><div class="eyebrow">Tanjung Bintang</div><h1>Jastip & Kurir</h1><p>Kirim barang, titip belanja, dan pantau pesanan dengan mudah.</p><button class="btn btn-white" data-nav="send"><span class="material-symbols-outlined">add</span>Kirim Barang</button></section><div class="section-title">Layanan</div><div class="grid3"><button class="service" data-nav="send"><div class="icon"><span class="material-symbols-outlined">package_2</span></div><h3>Kirim Barang</h3><p>Kurir cepat dari lokasi Anda ke tujuan.</p></button><button class="service" data-nav="store"><div class="icon"><span class="material-symbols-outlined">shopping_bag</span></div><h3>Jastip & Store</h3><p>Belanja makanan dan barang melalui kami.</p></button><button class="service" data-nav="orders"><div class="icon"><span class="material-symbols-outlined">route</span></div><h3>Lacak Pesanan</h3><p>Lihat status dan perjalanan pesanan.</p></button></div><div class="quick-row"><button class="quick" data-nav="send"><span class="material-symbols-outlined">bolt</span>Express</button><button class="quick" data-nav="store"><span class="material-symbols-outlined">restaurant</span>Food</button><button class="quick" data-nav="orders"><span class="material-symbols-outlined">location_on</span>Tracking</button><button class="quick" data-nav="profile"><span class="material-symbols-outlined">support_agent</span>Bantuan</button></div><div class="promo"><div><strong>Antar cepat di Tanjung Bintang</strong><br><span>Pesan sekarang, kami bantu sampai tujuan.</span></div><span class="material-symbols-outlined" style="font-size:42px;color:var(--green)">two_wheeler</span></div>`}
function sendPage(prefill=''){return `<div class="section-title" style="margin-top:4px">Buat Pesanan</div><div class="card"><div class="form"><div><div class="label">Jenis layanan</div><div class="option-row"><button class="option active" data-service="Kirim Barang"><strong>📦 Kirim</strong><span>Barang Anda</span></button><button class="option" data-service="Jastip"><strong>🛍️ Jastip</strong><span>Titip belanja</span></button><button class="option" data-service="Food"><strong>🍜 Food</strong><span>Pesan makanan</span></button></div></div><div class="route"><div><div class="route-dot"></div><div class="route-line"></div><div class="route-dot red"></div></div><div class="form"><div><div class="label">Lokasi pickup</div><input id="from" class="field" placeholder="Contoh: Tanjung Bintang, Lampung Selatan"></div><div><div class="label">Lokasi tujuan</div><input id="to" class="field" placeholder="Contoh: Jatibaru, Tanjung Bintang"></div></div></div><div><div class="label">Detail barang / belanjaan</div><textarea id="notes" class="field" placeholder="Contoh: 1 paket, makanan, ukuran, catatan kurir...">${esc(prefill)}</textarea></div><div><div class="label">Pilihan pengantaran</div><div class="option-row"><button class="option active" data-speed="Express"><strong>⚡ Express</strong><span>Prioritas</span></button><button class="option" data-speed="Reguler"><strong>🛵 Reguler</strong><span>Lebih hemat</span></button><button class="option" data-speed="Terjadwal"><strong>🗓️ Jadwal</strong><span>Pilih waktu</span></button></div></div><div><div class="label">Pembayaran</div><select id="payment" class="field"><option>COD</option><option>Transfer</option><option>Bayar saat selesai</option></select></div><div class="sticky-action"><button class="btn btn-primary" style="width:100%" id="submitOrder"><span class="material-symbols-outlined">check_circle</span>Pesan Sekarang</button></div></div></div>`}
function ordersPage(){if(!orders.length)return `<div class="section-title" style="margin-top:4px">Pesanan Saya</div><div class="card center"><span class="material-symbols-outlined" style="font-size:45px;color:var(--green)">inventory_2</span><h3>Belum ada pesanan</h3><p class="muted">Pesanan yang Anda buat akan muncul di sini.</p><button class="btn btn-primary" data-nav="send">Buat Pesanan</button></div>`;return `<div class="section-title" style="margin-top:4px">Pesanan Saya</div><div class="card"><div class="list">${orders.map(o=>`<button class="row order" data-order="${esc(o.id)}" style="text-align:left;background:none;width:100%"><div class="order-icon"><span class="material-symbols-outlined">package_2</span></div><div class="order-main"><strong>${esc(o.id)}</strong><small>${esc(o.service||'Kirim Barang')} • ${esc(o.to||'-')}</small><small>${o.total?money(o.total):'Harga akan dikonfirmasi admin'} • ${dt(o.createdAt)}</small></div>${statusBadge(o.status)}</button>`).join('')}</div></div>`}
function profilePage(){return `<div class="section-title" style="margin-top:4px">Profil</div><div class="card"><div class="profile-head"><div class="avatar" style="display:grid;place-items:center"><span class="material-symbols-outlined" style="font-size:30px;color:var(--green)">person</span></div><div><strong>${esc(profile?.name||user?.email||'Pelanggan')}</strong><div class="muted" style="font-size:11px">${esc(user?.email||'')}</div></div></div><div class="row"><span>Nomor pelanggan</span><strong style="font-size:11px">${esc(user?.uid?.slice(0,10)||'-')}</strong></div><div class="row"><span>Area layanan</span><strong style="font-size:11px">Tanjung Bintang</strong></div><button class="btn btn-danger" style="width:100%;margin-top:8px" id="logout">Keluar</button></div><div class="section-title">Bantuan</div><div class="card"><button class="row linkrow" data-help="wa"><span>📞 Hubungi admin</span><span>›</span></button><div class="row"><span>📍 Area layanan</span><span>Tanjung Bintang</span></div><div class="row"><span>ℹ️ Tentang TB Express</span><span>›</span></div></div>`}
function storePage(){const list=products.length?products.filter(p=>p.active!==false):demoProducts;return `<div class="section-title" style="margin-top:4px">Jastip & Store</div><div class="promo" style="margin-top:0"><div><strong>Belanja, kami yang ambil & antar</strong><br><span>Pilih layanan atau produk yang ingin dititipkan.</span></div><span style="font-size:38px">🛵</span></div><div class="section-title">Pilihan layanan</div><div class="list">${list.map(p=>`<button class="card product-card" style="display:flex;align-items:center;text-align:left;gap:12px;width:100%" data-product="${esc(p.id)}"><div style="font-size:34px">${esc(p.icon||'🛍️')}</div><div style="flex:1"><strong>${esc(p.name)}</strong><div class="muted" style="font-size:10px">${esc(p.category||'Jastip')}</div></div><strong style="font-size:11px;color:var(--green)">${money(p.price)}</strong></button>`).join('')}</div>`}
function trackingPage(o){const from=o?.from||'Tanjung Bintang, Lampung Selatan',to=o?.to||'Tanjung Bintang, Lampung Selatan';return `<div class="section-title" style="margin-top:4px">Lacak Pesanan</div><div class="card"><div style="display:flex;justify-content:space-between;gap:10px"><div><strong>${esc(o.id)}</strong><div class="muted" style="font-size:10px">${esc(o.service||'Kirim Barang')}</div></div>${statusBadge(o.status)}</div><div class="map" style="margin-top:14px"><div class="map-label">📍 Rute Pesanan</div><div class="road"></div><div class="route-line-map"></div><div class="pin a">📍</div><div class="pin b">🏁</div></div><div class="grid3" style="margin-top:12px"><div class="card" style="padding:10px;text-align:center"><small>Pickup</small><strong style="display:block;font-size:11px">${esc(from)}</strong></div><div class="card" style="padding:10px;text-align:center"><small>Status</small><strong style="display:block;font-size:11px">${esc(o.status)}</strong></div><div class="card" style="padding:10px;text-align:center"><small>Tujuan</small><strong style="display:block;font-size:11px">${esc(to)}</strong></div></div><button class="btn btn-primary" style="width:100%;margin-top:12px" id="mapsBtn"><span class="material-symbols-outlined">map</span>Buka Rute Google Maps</button>${o.status==='Menunggu'?`<button class="btn btn-danger" style="width:100%;margin-top:8px" id="cancelOrder">Batalkan Pesanan</button>`:''}</div>`}
function bindCommon(){ $$('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;selectedOrder=null;render()}); const lo=$('#logout');if(lo)lo.onclick=logout; $$('[data-product]').forEach(b=>b.onclick=()=>{const p=(products.length?products:demoProducts).find(x=>x.id===b.dataset.product)||demoProducts.find(x=>x.id===b.dataset.product);view='send';render();setTimeout(()=>{const n=$('#notes');if(n)n.value=`Titip ${p?.name||''}`},30)});$$('[data-order]').forEach(b=>b.onclick=()=>{selectedOrder=orders.find(x=>x.id===b.dataset.order);if(selectedOrder){view='tracking';render()}});$$('[data-help]').forEach(b=>b.onclick=()=>toast('Hubungi admin melalui WhatsApp yang Anda gunakan untuk pemesanan.'))}
function bindSend(){ $$('[data-service]').forEach(b=>b.onclick=()=>{$$('[data-service]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$$('[data-speed]').forEach(b=>b.onclick=()=>{$$('[data-speed]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});const s=$('#submitOrder');if(s)s.onclick=createOrder}
async function createOrder(){if(!user){showLogin();return}const from=$('#from')?.value.trim(),to=$('#to')?.value.trim(),notes=$('#notes')?.value.trim();if(!from||!to){toast('Lokasi pickup dan tujuan wajib diisi');return}const service=$('[data-service].active')?.dataset.service||'Kirim Barang',speed=$('[data-speed].active')?.dataset.speed||'Express';try{await addDoc(collection(db,'orders'),{userId:user.uid,customer:profile?.name||user.email,customerEmail:user.email,service,speed,from,to,notes,payment:$('#payment')?.value||'COD',status:'Menunggu',total:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});toast('Pesanan berhasil dibuat');view='orders';render()}catch(e){console.error(e);toast('Pesanan gagal: '+(e.code||e.message))}}
function render(){if(!user){showLogin();return}if(profile?.role==='admin'){renderAdmin();return}if(view==='tracking'){customerLayout(trackingPage(selectedOrder||orders[0]));const mb=$('#mapsBtn');if(mb)mb.onclick=()=>{const o=selectedOrder||orders[0]||{};window.open('https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(o.from||'Tanjung Bintang, Lampung Selatan')+'&destination='+encodeURIComponent(o.to||'Tanjung Bintang, Lampung Selatan'),'_blank')};const cb=$('#cancelOrder');if(cb)cb.onclick=async()=>{try{await updateDoc(doc(db,'orders',selectedOrder.id),{status:'Dibatalkan',updatedAt:serverTimestamp()});toast('Pesanan dibatalkan');view='orders';render()}catch(e){toast('Gagal membatalkan pesanan')}}}else if(view==='send'){customerLayout(sendPage());bindSend()}else if(view==='orders'){customerLayout(ordersPage())}else if(view==='profile'){customerLayout(profilePage())}else if(view==='store'){customerLayout(storePage())}else{customerLayout(home())}}
function showLogin(){let mode='login';$('#app').innerHTML=`<div class="login"><div class="login-card"><img class="login-logo" src="assets/logo.png"><div class="center"><div class="eyebrow" style="color:var(--green)">TB EXPRESS</div><h1 style="font-size:24px;margin:5px 0">Jastip & Kurir</h1><p class="muted" style="font-size:12px">Masuk untuk memesan, melacak, dan mengelola pesanan.</p></div><div id="loginForm"></div></div></div>`;const form=()=>{$('#loginForm').innerHTML=`<div class="form"><div><div class="label">Email</div><input id="email" class="field" type="email" placeholder="email@contoh.com"></div><div><div class="label">Password</div><input id="password" class="field" type="password" placeholder="••••••••"></div><button class="btn btn-primary" id="authSubmit" style="width:100%">${mode==='login'?'Masuk':'Daftar Akun'}</button><button class="btn btn-outline" id="switchAuth" style="width:100%">${mode==='login'?'Belum punya akun? Daftar':'Sudah punya akun? Masuk'}</button><div class="center muted" style="font-size:10px">Role admin dibaca dari Firestore. Jangan memilih role admin saat daftar.</div></div>`;$('#authSubmit').onclick=async()=>{try{const email=$('#email').value.trim(),password=$('#password').value;if(!email||!password)return toast('Email dan password wajib diisi');if(mode==='login'){await signInWithEmailAndPassword(auth,email,password)}else{const cr=await createUserWithEmailAndPassword(auth,email,password);await setDoc(doc(db,'users',cr.user.uid),{email,role:'customer',name:email.split('@')[0],createdAt:serverTimestamp()})}}catch(e){toast(e.code==='auth/invalid-credential'?'Email atau password salah':e.message)}};$('#switchAuth').onclick=()=>{mode=mode==='login'?'register':'login';form()}};form()}
async function logout(){await signOut(auth);view='home';selectedOrder=null;orders=[];profile=null;render()}
function adminShell(body){const menu=[['dashboard','dashboard','Dashboard'],['orders','receipt_long','Pesanan'],['customers','group','Pelanggan'],['products','inventory_2','Produk & Store'],['reports','bar_chart','Laporan']];$('#app').innerHTML=`<div class="admin-shell">${topbar(true)}<div class="admin-layout"><aside class="sidebar">${menu.map(m=>`<button class="sidebtn ${view==='admin-'+m[0]?'active':''}" data-admin="${m[0]}"><span class="material-symbols-outlined">${m[1]}</span>${m[2]}</button>`).join('')}</aside><main class="admin-main">${body}</main></div></div>`;$$('[data-admin]').forEach(b=>b.onclick=()=>{view='admin-'+b.dataset.admin;render()});$('#logout').onclick=logout}
function renderAdmin(){const body=view==='admin-orders'?adminOrders():view==='admin-customers'?adminCustomers():view==='admin-products'?adminProducts():view==='admin-reports'?adminReports():adminDashboard();adminShell(body);bindAdminBody()}
function adminDashboard(){const list=orders,count=s=>list.filter(x=>x.status===s).length;return `<div class="admin-head"><div><div class="muted">Operasional hari ini</div><h1>Dashboard Admin</h1></div><span class="badge green">Online</span></div><div class="kpis"><div class="kpi"><small>Total Pesanan</small><strong>${list.length}</strong></div><div class="kpi"><small>Menunggu</small><strong>${count('Menunggu')}</strong></div><div class="kpi"><small>Dikirim</small><strong>${count('Dikirim')}</strong></div><div class="kpi"><small>Selesai</small><strong>${count('Selesai')}</strong></div></div><div class="section-title">Pesanan Terbaru</div><div class="card table-card"><table class="table"><thead><tr><th>ID</th><th>Pelanggan</th><th>Layanan</th><th>Tujuan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${list.slice(0,10).map(o=>`<tr><td><strong>${esc(o.id)}</strong></td><td>${esc(o.customer||o.customerEmail||'-')}</td><td>${esc(o.service||'-')}</td><td>${esc(o.to||'-')}</td><td>${statusBadge(o.status)}</td><td><button class="btn btn-outline" data-detail="${esc(o.id)}" style="padding:7px 9px;font-size:10px">Kelola</button></td></tr>`).join('')||'<tr><td colspan="6">Belum ada pesanan.</td></tr>'}</tbody></table></div>`}
function adminOrders(){return `<div class="admin-head"><div><div class="muted">Dispatch & operasional</div><h1>Kelola Pesanan</h1></div></div><div class="card table-card" style="margin-top:15px"><table class="table"><thead><tr><th>ID</th><th>Pelanggan</th><th>Rute</th><th>Layanan</th><th>Status</th><th>Harga</th><th>Ubah</th></tr></thead><tbody>${orders.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.customer||o.customerEmail||'-')}</td><td>${esc(o.from||'-')} → ${esc(o.to||'-')}</td><td>${esc(o.service||'-')} / ${esc(o.speed||'-')}</td><td>${statusBadge(o.status)}</td><td><input class="field price-input" data-id="${esc(o.id)}" type="number" value="${Number(o.total)||0}" style="width:110px;padding:7px"></td><td><select class="field status-select" data-id="${esc(o.id)}" style="padding:7px"><option ${o.status==='Menunggu'?'selected':''}>Menunggu</option><option ${o.status==='Diproses'?'selected':''}>Diproses</option><option ${o.status==='Dijemput'?'selected':''}>Dijemput</option><option ${o.status==='Dikirim'?'selected':''}>Dikirim</option><option ${o.status==='Selesai'?'selected':''}>Selesai</option><option ${o.status==='Dibatalkan'?'selected':''}>Dibatalkan</option></select></td></tr>`).join('')||'<tr><td colspan="7">Belum ada pesanan.</td></tr>'}</tbody></table></div>`}
function adminCustomers(){return `<div class="admin-head"><div><div class="muted">Database pengguna</div><h1>Pelanggan</h1></div></div><div class="card table-card"><table class="table"><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Bergabung</th></tr></thead><tbody>${customers.map(c=>`<tr><td>${esc(c.name||'-')}</td><td>${esc(c.email||'-')}</td><td>${esc(c.role||'customer')}</td><td>${dt(c.createdAt)}</td></tr>`).join('')||'<tr><td colspan="4">Belum ada data pelanggan.</td></tr>'}</tbody></table></div>`}
function adminProducts(){const list=products;return `<div class="admin-head"><div><div class="muted">Katalog yang tampil di Store customer</div><h1>Produk & Store</h1></div><button class="btn btn-primary" id="addProduct">+ Tambah Produk</button></div><div class="grid3" style="margin-top:15px">${list.map(p=>`<div class="card"><div style="font-size:34px">${esc(p.icon||'🛍️')}</div><h3>${esc(p.name)}</h3><p class="muted">${esc(p.category||'-')} • ${money(p.price)}</p><div style="display:flex;gap:6px"><button class="btn btn-outline" data-edit-product="${esc(p.id)}">Edit</button><button class="btn btn-danger" data-delete-product="${esc(p.id)}">Hapus</button></div></div>`).join('')||'<div class="card">Belum ada produk.</div>'}</div>`}
function adminReports(){const total=orders.reduce((a,b)=>a+(Number(b.total)||0),0);return `<div class="admin-head"><div><div class="muted">Rekap transaksi</div><h1>Laporan</h1></div><button class="btn btn-primary" id="exportCsv">Export CSV</button></div><div class="kpis"><div class="kpi"><small>Total Pesanan</small><strong>${orders.length}</strong></div><div class="kpi"><small>Total Omzet</small><strong>${money(total)}</strong></div><div class="kpi"><small>Selesai</small><strong>${orders.filter(x=>x.status==='Selesai').length}</strong></div><div class="kpi"><small>Dibatalkan</small><strong>${orders.filter(x=>x.status==='Dibatalkan').length}</strong></div></div><div class="card table-card" style="margin-top:15px"><table class="table"><thead><tr><th>Tanggal</th><th>ID</th><th>Pelanggan</th><th>Layanan</th><th>Status</th><th>Total</th></tr></thead><tbody>${orders.map(o=>`<tr><td>${dt(o.createdAt)}</td><td>${esc(o.id)}</td><td>${esc(o.customer||o.customerEmail||'-')}</td><td>${esc(o.service||'-')}</td><td>${statusBadge(o.status)}</td><td>${money(o.total)}</td></tr>`).join('')||'<tr><td colspan="6">Belum ada transaksi.</td></tr>'}</tbody></table></div>`}
function bindAdminBody(){
  $$('[data-detail]').forEach(b=>b.onclick=()=>showAdminOrder(b.dataset.detail));
  $$('.status-select').forEach(s=>s.onchange=()=>updateOrderStatus(s.dataset.id,s.value));
  $$('.price-input').forEach(i=>i.onchange=()=>updateOrderPrice(i.dataset.id,i.value));
  const ep=$('#exportCsv');if(ep)ep.onclick=exportCsv;
  const ap=$('#addProduct');if(ap)ap.onclick=()=>productForm();
  $$('[data-edit-product]').forEach(b=>b.onclick=()=>productForm(products.find(p=>p.id===b.dataset.editProduct)));
  $$('[data-delete-product]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.deleteProduct));
}
async function updateOrderStatus(id,status){try{await updateDoc(doc(db,'orders',id),{status,updatedAt:serverTimestamp()});await addDoc(collection(db,'tracking'),{orderId:id,status,createdAt:serverTimestamp(),by:user.uid});toast('Status pesanan diperbarui')}catch(e){console.error(e);toast('Gagal mengubah status: '+e.message)}}
async function updateOrderPrice(id,value){try{await updateDoc(doc(db,'orders',id),{total:Number(value)||0,updatedAt:serverTimestamp()});toast('Harga disimpan')}catch(e){toast('Gagal menyimpan harga')}}
function showAdminOrder(id){const o=orders.find(x=>x.id===id);if(!o)return;selectedOrder=o;appModal(`<h2>Detail Pesanan ${esc(o.id)}</h2><div class="card"><div class="row"><span>Pelanggan</span><strong>${esc(o.customer||o.customerEmail||'-')}</strong></div><div class="row"><span>Layanan</span><strong>${esc(o.service||'-')} / ${esc(o.speed||'-')}</strong></div><div class="row"><span>Pickup</span><strong>${esc(o.from||'-')}</strong></div><div class="row"><span>Tujuan</span><strong>${esc(o.to||'-')}</strong></div><div class="row"><span>Catatan</span><strong>${esc(o.notes||'-')}</strong></div><div class="row"><span>Pembayaran</span><strong>${esc(o.payment||'-')}</strong></div><div class="row"><span>Total</span><strong>${money(o.total)}</strong></div><div style="display:flex;gap:8px;margin-top:12px"><button class="btn btn-primary" id="modalMap">Buka Google Maps</button><button class="btn btn-outline" id="modalClose">Tutup</button></div></div>`);$('#modalMap').onclick=()=>window.open('https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(o.from||'')+'&destination='+encodeURIComponent(o.to||''),'_blank');$('#modalClose').onclick=closeModal}
function appModal(content){let m=$('#appModal');if(!m){m=document.createElement('div');m.id='appModal';m.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:9999;display:grid;place-items:center;padding:20px';document.body.appendChild(m)}m.innerHTML=`<div class="card" style="width:min(520px,100%);max-height:90vh;overflow:auto">${content}</div>`;m.style.display='grid'}
function closeModal(){const m=$('#appModal');if(m)m.style.display='none'}
function productForm(p=null){appModal(`<h2>${p?'Edit Produk':'Tambah Produk'}</h2><div class="form"><input id="pname" class="field" placeholder="Nama produk" value="${esc(p?.name||'')}"><input id="pcat" class="field" placeholder="Kategori" value="${esc(p?.category||'Food')}"><input id="pprice" class="field" type="number" placeholder="Harga" value="${Number(p?.price)||0}"><input id="picon" class="field" placeholder="Emoji / ikon" value="${esc(p?.icon||'🛍️')}"><div style="display:flex;gap:8px"><button class="btn btn-primary" id="saveProduct">Simpan</button><button class="btn btn-outline" id="closeProduct">Batal</button></div></div>`);$('#closeProduct').onclick=closeModal;$('#saveProduct').onclick=async()=>{const data={name:$('#pname').value.trim(),category:$('#pcat').value.trim()||'Jastip',price:Number($('#pprice').value)||0,icon:$('#picon').value.trim()||'🛍️',active:true,updatedAt:serverTimestamp()};if(!data.name)return toast('Nama produk wajib diisi');try{if(p)await updateDoc(doc(db,'products',p.id),data);else await addDoc(collection(db,'products'),{...data,createdAt:serverTimestamp()});toast('Produk tersimpan');closeModal()}catch(e){toast('Gagal menyimpan produk: '+e.message)}}}
async function deleteProduct(id){if(!confirm('Hapus produk ini?'))return;try{await deleteDoc(doc(db,'products',id));toast('Produk dihapus')}catch(e){toast('Gagal menghapus produk')}}
function exportCsv(){const head=['Tanggal','ID','Pelanggan','Layanan','Kecepatan','Pickup','Tujuan','Status','Pembayaran','Total'];const rows=orders.map(o=>[dt(o.createdAt),o.id,o.customer||o.customerEmail||'',o.service||'',o.speed||'',o.from||'',o.to||'',o.status||'',o.payment||'',o.total||0]);const csv=[head,...rows].map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='laporan-tb-express.csv';a.click();URL.revokeObjectURL(a.href)}
async function getProfile(u){const snap=await getDoc(doc(db,'users',u.uid));if(snap.exists())return snap.data();const fallback={email:u.email,role:'customer',name:u.email?.split('@')[0]||'Pelanggan'};await setDoc(doc(db,'users',u.uid),fallback,{merge:true});return fallback}
function listenOrders(){if(unsubscribeOrders)unsubscribeOrders();if(!user)return;const q=profile?.role==='admin'?query(collection(db,'orders')):query(collection(db,'orders'),where('userId','==',user.uid));unsubscribeOrders=onSnapshot(q,s=>{orders=s.docs.map(d=>({id:d.id,...d.data()}));render()},e=>{console.error(e);orders=[];render();toast('Gagal membaca pesanan. Cek Firestore Rules.')})}
function listenProducts(){if(unsubscribeProducts)unsubscribeProducts();if(!user)return;unsubscribeProducts=onSnapshot(collection(db,'products'),s=>{products=s.docs.map(d=>({id:d.id,...d.data()}));if(view==='store'||profile?.role==='admin')render()},e=>console.error(e))}
function listenCustomers(){if(unsubscribeUsers)unsubscribeUsers();if(!user||profile?.role!=='admin')return;unsubscribeUsers=onSnapshot(collection(db,'users'),s=>{customers=s.docs.map(d=>({id:d.id,...d.data()}));if(view==='admin-customers')render()},e=>console.error(e))}
onAuthStateChanged(auth,async u=>{user=u;if(unsubscribeOrders)unsubscribeOrders();if(unsubscribeProducts)unsubscribeProducts();if(unsubscribeUsers)unsubscribeUsers();if(u){profile=await getProfile(u);await Promise.all([Promise.resolve(listenOrders()),Promise.resolve(listenProducts()),Promise.resolve(listenCustomers())])}else{profile=null;orders=[];products=[];customers=[]}render()});
